### ISSUE TITLE
Build a static site

### ISSUE THREAD

**Issue by khos2ow** [opensourcecities/berlin#1]
This is to propose porting static website template, implemented with [Hugo](https://gohugo.io), from [Montreal](https://github.com/opensourcecities/montreal) repo to here. You can check the Montreal site in action [here](https://opensourcecities.github.io/montreal/).

The site will be accessible on [https://opensourcecities.github.io/berlin/](https://opensourcecities.github.io/berlin/). I would like to know if you have any suggestions, comments or concerns on this.

**Comment by RichardLitt** [comment]
Not sure there's really that much interest in this list at the moment. Let's reopen in a few months.

**Comment by khos2ow** [comment]
Sure.
